// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pb/demoa/demoa.proto

package demoa

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDriverTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverTagsRequest) Reset() {
	*x = GetDriverTagsRequest{}
	mi := &file_pb_demo_demo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverTagsRequest) ProtoMessage() {}

func (x *GetDriverTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_demo_demo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverTagsRequest.ProtoReflect.Descriptor instead.
func (*GetDriverTagsRequest) Descriptor() ([]byte, []int) {
	return file_pb_demo_demo_proto_rawDescGZIP(), []int{0}
}

type GetDriverTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DebugMsg      *string                `protobuf:"bytes,1,opt,name=debug_msg,json=debugMsg,proto3,oneof" json:"debug_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverTagsResponse) Reset() {
	*x = GetDriverTagsResponse{}
	mi := &file_pb_demo_demo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverTagsResponse) ProtoMessage() {}

func (x *GetDriverTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_demo_demo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverTagsResponse.ProtoReflect.Descriptor instead.
func (*GetDriverTagsResponse) Descriptor() ([]byte, []int) {
	return file_pb_demo_demo_proto_rawDescGZIP(), []int{1}
}

func (x *GetDriverTagsResponse) GetDebugMsg() string {
	if x != nil && x.DebugMsg != nil {
		return *x.DebugMsg
	}
	return ""
}

var File_pb_demo_demo_proto protoreflect.FileDescriptor

const file_pb_demo_demo_proto_rawDesc = "" +
	"\n" +
	"\x12pb/demoa/demoa.proto\"\x16\n" +
	"\x14GetDriverTagsRequest\"G\n" +
	"\x15GetDriverTagsResponse\x12 \n" +
	"\tdebug_msg\x18\x01 \x01(\tH\x00R\bdebugMsg\x88\x01\x01B\f\n" +
	"\n" +
	"_debug_msg2H\n" +
	"\x04Demo\x12@\n" +
	"\rGetDriverTags\x12\x15.GetDriverTagsRequest\x1a\x16.GetDriverTagsResponse\"\x00B\tZ\a./;demob\x06proto3"

var (
	file_pb_demo_demo_proto_rawDescOnce sync.Once
	file_pb_demo_demo_proto_rawDescData []byte
)

func file_pb_demo_demo_proto_rawDescGZIP() []byte {
	file_pb_demo_demo_proto_rawDescOnce.Do(func() {
		file_pb_demo_demo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_demo_demo_proto_rawDesc), len(file_pb_demo_demo_proto_rawDesc)))
	})
	return file_pb_demo_demo_proto_rawDescData
}

var file_pb_demo_demo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_demo_demo_proto_goTypes = []any{
	(*GetDriverTagsRequest)(nil),  // 0: GetDriverTagsRequest
	(*GetDriverTagsResponse)(nil), // 1: GetDriverTagsResponse
}
var file_pb_demo_demo_proto_depIdxs = []int32{
	0, // 0: Demo.GetDriverTags:input_type -> GetDriverTagsRequest
	1, // 1: Demo.GetDriverTags:output_type -> GetDriverTagsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_demo_demo_proto_init() }
func file_pb_demo_demo_proto_init() {
	if File_pb_demo_demo_proto != nil {
		return
	}
	file_pb_demo_demo_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_demo_demo_proto_rawDesc), len(file_pb_demo_demo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_demo_demo_proto_goTypes,
		DependencyIndexes: file_pb_demo_demo_proto_depIdxs,
		MessageInfos:      file_pb_demo_demo_proto_msgTypes,
	}.Build()
	File_pb_demo_demo_proto = out.File
	file_pb_demo_demo_proto_goTypes = nil
	file_pb_demo_demo_proto_depIdxs = nil
}
