log:
  Level: info
  Path: log
  MaxSize: 1024       # megabytes
  MaxBackups: 30
  MaxAge: 3          # days
  BufferSize: 4194304
  ChannelSize: 32768
  EnableCaller: true
  EnableConsole: true
  ErrorAsync: false

Server:
  Name: buy
  ListenOn: 0.0.0.0:8081
  Etcd:
    Hosts:
      - 127.0.0.1:2379
    Key: buy