// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pb/demo/demo.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RateDriverByOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       *uint64                `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3,oneof" json:"order_id,omitempty"`
	BuyerId       *uint64                `protobuf:"varint,2,opt,name=buyer_id,json=buyerId,proto3,oneof" json:"buyer_id,omitempty"`
	DriverId      *uint64                `protobuf:"varint,3,opt,name=driver_id,json=driverId,proto3,oneof" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateDriverByOrderRequest) Reset() {
	*x = RateDriverByOrderRequest{}
	mi := &file_pb_demo_demo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateDriverByOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateDriverByOrderRequest) ProtoMessage() {}

func (x *RateDriverByOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_demo_demo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateDriverByOrderRequest.ProtoReflect.Descriptor instead.
func (*RateDriverByOrderRequest) Descriptor() ([]byte, []int) {
	return file_pb_demo_demo_proto_rawDescGZIP(), []int{0}
}

func (x *RateDriverByOrderRequest) GetOrderId() uint64 {
	if x != nil && x.OrderId != nil {
		return *x.OrderId
	}
	return 0
}

func (x *RateDriverByOrderRequest) GetBuyerId() uint64 {
	if x != nil && x.BuyerId != nil {
		return *x.BuyerId
	}
	return 0
}

func (x *RateDriverByOrderRequest) GetDriverId() uint64 {
	if x != nil && x.DriverId != nil {
		return *x.DriverId
	}
	return 0
}

type RateDriverByOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DebugMsg      *string                `protobuf:"bytes,1,opt,name=debug_msg,json=debugMsg,proto3,oneof" json:"debug_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateDriverByOrderResponse) Reset() {
	*x = RateDriverByOrderResponse{}
	mi := &file_pb_demo_demo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateDriverByOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateDriverByOrderResponse) ProtoMessage() {}

func (x *RateDriverByOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_demo_demo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateDriverByOrderResponse.ProtoReflect.Descriptor instead.
func (*RateDriverByOrderResponse) Descriptor() ([]byte, []int) {
	return file_pb_demo_demo_proto_rawDescGZIP(), []int{1}
}

func (x *RateDriverByOrderResponse) GetDebugMsg() string {
	if x != nil && x.DebugMsg != nil {
		return *x.DebugMsg
	}
	return ""
}

var File_pb_demo_demo_proto protoreflect.FileDescriptor

const file_pb_demo_demo_proto_rawDesc = "" +
	"\n" +
	"\x12pb/demo/demo.proto\"\xa4\x01\n" +
	"\x18RateDriverByOrderRequest\x12\x1e\n" +
	"\border_id\x18\x01 \x01(\x04H\x00R\aorderId\x88\x01\x01\x12\x1e\n" +
	"\bbuyer_id\x18\x02 \x01(\x04H\x01R\abuyerId\x88\x01\x01\x12 \n" +
	"\tdriver_id\x18\x03 \x01(\x04H\x02R\bdriverId\x88\x01\x01B\v\n" +
	"\t_order_idB\v\n" +
	"\t_buyer_idB\f\n" +
	"\n" +
	"_driver_id\"K\n" +
	"\x19RateDriverByOrderResponse\x12 \n" +
	"\tdebug_msg\x18\x01 \x01(\tH\x00R\bdebugMsg\x88\x01\x01B\f\n" +
	"\n" +
	"_debug_msg2T\n" +
	"\x04Demo\x12L\n" +
	"\x11RateDriverByOrder\x12\x19.RateDriverByOrderRequest\x1a\x1a.RateDriverByOrderResponse\"\x00B\aZ\x05./;pbb\x06proto3"

var (
	file_pb_demo_demo_proto_rawDescOnce sync.Once
	file_pb_demo_demo_proto_rawDescData []byte
)

func file_pb_demo_demo_proto_rawDescGZIP() []byte {
	file_pb_demo_demo_proto_rawDescOnce.Do(func() {
		file_pb_demo_demo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_demo_demo_proto_rawDesc), len(file_pb_demo_demo_proto_rawDesc)))
	})
	return file_pb_demo_demo_proto_rawDescData
}

var file_pb_demo_demo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_demo_demo_proto_goTypes = []any{
	(*RateDriverByOrderRequest)(nil),  // 0: RateDriverByOrderRequest
	(*RateDriverByOrderResponse)(nil), // 1: RateDriverByOrderResponse
}
var file_pb_demo_demo_proto_depIdxs = []int32{
	0, // 0: Demo.RateDriverByOrder:input_type -> RateDriverByOrderRequest
	1, // 1: Demo.RateDriverByOrder:output_type -> RateDriverByOrderResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_demo_demo_proto_init() }
func file_pb_demo_demo_proto_init() {
	if File_pb_demo_demo_proto != nil {
		return
	}
	file_pb_demo_demo_proto_msgTypes[0].OneofWrappers = []any{}
	file_pb_demo_demo_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_demo_demo_proto_rawDesc), len(file_pb_demo_demo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_demo_demo_proto_goTypes,
		DependencyIndexes: file_pb_demo_demo_proto_depIdxs,
		MessageInfos:      file_pb_demo_demo_proto_msgTypes,
	}.Build()
	File_pb_demo_demo_proto = out.File
	file_pb_demo_demo_proto_goTypes = nil
	file_pb_demo_demo_proto_depIdxs = nil
}
