// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/lee31802/gotemplate/buysrv/biz"
	"github.com/lee31802/gotemplate/buysrv/dao"
	"github.com/lee31802/gotemplate/buysrv/handler"
	"github.com/lee31802/gotemplate/buysrv/service"
)

// Injectors from wire.go:

func InitializeHandler() *handler.BuyHandler {
	buyDao := dao.NewBuyDao()
	buyService := service.NewBuyService(buyDao)
	buyBiz := biz.NewBuyBiz(buyService)
	buyHandler := handler.NewBuyHandler(buyBiz)
	return buyHandler
}
