// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pb/buy/buy.proto

package buy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        *int64                 `protobuf:"varint,1,opt,name=userId,proto3,oneof" json:"userId,omitempty"`
	ProductId     *int64                 `protobuf:"varint,2,opt,name=productId,proto3,oneof" json:"productId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_pb_buy_buy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_buy_buy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_pb_buy_buy_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderRequest) GetUserId() int64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *CreateOrderRequest) GetProductId() int64 {
	if x != nil && x.ProductId != nil {
		return *x.ProductId
	}
	return 0
}

type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       *string                `protobuf:"bytes,1,opt,name=orderId,proto3,oneof" json:"orderId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_pb_buy_buy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_buy_buy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_pb_buy_buy_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrderResponse) GetOrderId() string {
	if x != nil && x.OrderId != nil {
		return *x.OrderId
	}
	return ""
}

var File_pb_buy_buy_proto protoreflect.FileDescriptor

const file_pb_buy_buy_proto_rawDesc = "" +
	"\n" +
	"\x10pb/buy/buy.proto\"m\n" +
	"\x12CreateOrderRequest\x12\x1b\n" +
	"\x06userId\x18\x01 \x01(\x03H\x00R\x06userId\x88\x01\x01\x12!\n" +
	"\tproductId\x18\x02 \x01(\x03H\x01R\tproductId\x88\x01\x01B\t\n" +
	"\a_userIdB\f\n" +
	"\n" +
	"_productId\"@\n" +
	"\x13CreateOrderResponse\x12\x1d\n" +
	"\aorderId\x18\x01 \x01(\tH\x00R\aorderId\x88\x01\x01B\n" +
	"\n" +
	"\b_orderId2?\n" +
	"\x03Buy\x128\n" +
	"\vCreateOrder\x12\x13.CreateOrderRequest\x1a\x14.CreateOrderResponseB\bZ\x06./;buyb\x06proto3"

var (
	file_pb_buy_buy_proto_rawDescOnce sync.Once
	file_pb_buy_buy_proto_rawDescData []byte
)

func file_pb_buy_buy_proto_rawDescGZIP() []byte {
	file_pb_buy_buy_proto_rawDescOnce.Do(func() {
		file_pb_buy_buy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_buy_buy_proto_rawDesc), len(file_pb_buy_buy_proto_rawDesc)))
	})
	return file_pb_buy_buy_proto_rawDescData
}

var file_pb_buy_buy_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_buy_buy_proto_goTypes = []any{
	(*CreateOrderRequest)(nil),  // 0: CreateOrderRequest
	(*CreateOrderResponse)(nil), // 1: CreateOrderResponse
}
var file_pb_buy_buy_proto_depIdxs = []int32{
	0, // 0: Buy.CreateOrder:input_type -> CreateOrderRequest
	1, // 1: Buy.CreateOrder:output_type -> CreateOrderResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_buy_buy_proto_init() }
func file_pb_buy_buy_proto_init() {
	if File_pb_buy_buy_proto != nil {
		return
	}
	file_pb_buy_buy_proto_msgTypes[0].OneofWrappers = []any{}
	file_pb_buy_buy_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_buy_buy_proto_rawDesc), len(file_pb_buy_buy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_buy_buy_proto_goTypes,
		DependencyIndexes: file_pb_buy_buy_proto_depIdxs,
		MessageInfos:      file_pb_buy_buy_proto_msgTypes,
	}.Build()
	File_pb_buy_buy_proto = out.File
	file_pb_buy_buy_proto_goTypes = nil
	file_pb_buy_buy_proto_depIdxs = nil
}
